export const SET_NEW_RESTAURANTS = 'SET_NEW_RESTAURANTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';

export const HIDE_NEW_RESTAURANTS_LOADER = 'HIDE_NEW_RESTAURANTS_LOADER';
export const HIDE_CATEGORIES_LOADER = 'HIDE_CATEGORIES_LOADER';
