export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const SET_IS_LOGGED_OUT = 'SET_IS_LOGGED_OUT';
export const SET_USER = 'SET_USER';

export const SET_LOGIN_ERRORS = 'SET_LOGIN_ERRORS';
export const SET_REGISTER_ERRORS = 'SET_REGISTER_ERRORS';

export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL';
export const TOGGLE_REGISTER_MODAL = 'TOGGLE_REGISTER_MODAL';
